Repository hyejungg/WishBoard, pull requests merged in 2021-09, with the labels that each got.

#220 Feature:#219
  app/src/main/java/com/hyeeyoung/wishboard/detail/ItemDetailActivity.java
  app/src/main/java/com/hyeeyoung/wishboard/util/DateFormatUtil.java
  app/src/main/res/layout/activity_item_detail.xml
Labels: feature, notification

#222 Feature_#221
  app/src/main/java/com/hyeeyoung/wishboard/config/SharedItemVM.java
  app/src/main/java/com/hyeeyoung/wishboard/remote/IRemoteService.java
  app/src/main/java/com/hyeeyoung/wishboard/remote/RemoteLib.java
  app/src/main/res/layout/fragment_home.xml
Labels: feature, cart

#223 Mod:#219
  app/src/main/java/com/hyeeyoung/wishboard/util/DateFormatUtil.java
Labels: mod, notification

#225 hotfix:#155
  app/src/main/java/com/hyeeyoung/wishboard/folder/FolderFragment.java
  app/src/main/res/layout/fragment_home.xml
Labels: bug, hotfix
